# yaml-language-server: $schema=https://gcpw.art/tvs/schemas/5.9.0.json

# Documented configuration file.
# Data that is required will be denoted as such. Anything that isn't required can be commented out / removed.
# More options are available than are in this file, and links are provided to relevant parts of the documentation.

##### VISUAL EFFECTS #####
# REFERENCE:
# https://greenhillplaza.notion.site/Visual-Effects-68ae52d438344b9598cd4ac86cc2a0e5
#
# These options control the picture and the window.
##########################

applicationTitle: cake table :3 # Optional. The title of the webpage; make it your own!
scanlines: true # Optional. Scanlines are enabled by default but if you don't want them you can set this to false. On a real CRT it's best to disable these and shadow masks.
shadowMask: aperture-grille # Optional. The default shadow mask to simulate a CRT screen. Values are slot-mask, dot-mask, or aperture-grille. To disable, set to false.
noise: 0.01 # Optional. Default amount of picture noise to apply
blur: 1 # Optional. Default amount of blur to apply to the picture; set to false to disable
bezel: flat # Optional. You can specify a bezel image to go around the outside of the screen. Values are none, cylindrical or flat.
animateChannelChange: false # Optional. By default the TV will shake the screen a bit when changing channels. If you want to disable this set to false.
changeChannelNoise: false # Optional. By default the TV will add noise to the picture when changing channels. If you want to disable this set to false.
# autoScale: false # Optional. By default the TV will scale to fit the window. If you want to disable this set to false.
# border: placeholders/border.png # Optional. You can specify a repeating pattern a background image around the outside of the screen
# warmup: false # Optional. By default the TV will warm up and cool down when you power it on and off. If you want to disable this set to false. If set to a number, it will be the duration of the warmup in seconds.

# Uncomment the lines below to use the digital cable box theme instead of the default on-screen displays
#osd:
#  theme: digital
#  primaryColor: "#1e8a54"
#  accentColor: "#15613b"

# Uncomment the lines below to use the Sat1992 theme inspired by early-90s C-band satellite TV
# osd:
#   theme: sat1992 # 1990's analog C-band satellite receiver theme
#   themeOptions:
#     # showChannelInterference: false # by default, we display overlays of interference when tuning to a new channel. Set this to false to disable those.
#     satellite: C1 # the default satellite for all channels to be on. If unset, only channels with a satellite option set will display one.
#     satellites: # you can define a list of different satellites; they'll be a letter and number combination followed by a 4-digit number representing the location in the sky
#       C1: 3600 # these are all arbitrary numbers
#       C3: 4100
#       C4: 4300
#       C5: 4550
#       G1: 4550
#       G2: 4700
#       G3: 5100
#       G4: 6200
#       T3: 6900

# Uncomment the lines below to use the Sat2007 theme inspired by mid-2000 satellite TV
osd:
  theme: sat2007
  primaryColor: "green" # Optional color overrides
  accentColor: "white"
#   # aspectRatioBehavior: stretch # Optional. The aspect ratio behavior of the screen. Values are stretch, letterbox, or hybrid. Defaults to hybrid.
#   themeOptions: # certain themes have additional options that can be set like this:
#     showMessageIcon: true # Show the message icon in the top bar
#     showChannelLockIcon: true # Show the channel lock icon in the top bar

# Uncomment the lines below to use the Sat2012 theme inspired by mid-2010 satellite TV
# osd:
#   theme: sat2012
#   aspectRatioBehavior: stretch # Optional. The aspect ratio behavior of the screen. Values are stretch, letterbox, or hybrid. Defaults to hybrid.
#   # primaryColor: red
#   # accentColor: black
#   themeOptions: # certain themes have additional options that can be set like this:
#     # providerLogo: placeholders/no-signal.png # Optional. The provider logo to show in the info OSD. If commented out or not set the default logo will be shown. If set to false no logo will be shown.
#     extraMenuItemsBefore: # Non-functional extra menu items can be added for asthetic purposes.
#       - Messages
#     extraMenuItemsAfter: # More non-functional menu items.
#       - CC
#       - Last 4
#       - Favorites
#       - Audio/Video
#       - Parental

# osd: false # You can disable the on-screen displays entirely by setting this to false.

# You can also disable parts of the OSD individually. The following options are available:
# osd:
#   tuner: false # You can disable the tuner OSD by setting this to false.
#   info: false # You can disable the info OSD by setting this to false.
#   receiver: false # You can disable the receiver OSD by setting this to false.

# Screen dimensions defaults can be overridden here. If you don't specify these the TV will be 640x480 by default.
# Not all channel content will scale to fit the screen; some content will always render at its native resolution (640x480)
# **Note**: If you change these values, be sure to reset your picture settings using `alt + r` or you won't see the changes.
# dimensions:
#   screenWidth: 1280 # Optional. The width of the screen in pixels.
#   screenHeight: 720 # Optional. The height of the screen in pixels.
#   # scaleX: 100 # Optional. The scale of the screen percentage-wise on the X axis. Default is 100.
#   # scaleY: 100 # Optional. The scale of the screen percentage-wise on the Y axis. Default is 100.

# inputMapping: # Optional. You can override the default keyboard commands here.
#   volumeUp: q # For any key you override, the default key will be unassigned.
#   volumeDown: a # The combos supported should be in lower-case; the keys supported can be found at https://github.com/madrobby/keymaster?tab=readme-ov-file#supported-keys
#   power: shift+p, enter # Using + will require multiple keys to be pressed at the same time. Using , will assign multiple combos to the same function.
#   # Important: the browser may have some reserved key combos that can't be overridden. If you're having trouble with a key combo, try another one.

# persistCurrentChannel: localstorage # Optional. By default TVS will change the active URL to include the current channel when manually changed. Other options are: localstorage, url, or false to disable.

# startup: # Optional. You can specify content to show when the TV is first powered on before going to the default channel.
#   content: # Required. The content to show on startup.
#     video: placeholders/hypercom-boot.mp4 # This can be any content engine; in this case it's a video.
#   duration: 3 # Required if the content engine doesn't support end detection. This is the duration in seconds to show the startup content before going to the channels.
#               # Setting duration to 0 will make the startup content play *indefinitely* until interrupted by the user changing the channel or powering off the TV.
#   displayOnPageLoad: true # Optional. By default the startup content will show when the page is loaded. If you want to disable this set to false.
#   displayOnPowerOn: true # Optional. By default the startup content will show when the TV is powered on using the power button. If you want to disable this set to false.

##### Webhooks #####
# You can set up webhooks to send data to external services when certain events happen, for the purpose of automation or integration.
# All requests are sent as GET requests with query parameters.
# This is for you to receive data *from* TVS only; you can't send data to TVS with these.
# webhooks: # Optional. You can set up webhooks to send data to external services when certain events happen.
#   channelChange: http://your-server/receive_update?channel={channel}&manual={isManualInput} # Optional. This is the URL that will be called when the channel changes. The channel number and whether it was a manual input will be sent as query parameters.
#   volumeChange: http://your-server/receive_update?volume={volume} # Optional. This is the URL that will be called when the volume changes. The volume level will be sent as a query parameter.
#   muteChange: http://your-server/receive_update?isMuting={isMuting} # Optional. This is the URL that will be called when the muting or unmuting. The mute state will be sent as a query parameter.

startUnmuted: true

##### CHANNELS #####
# REFERENCE:
# https://greenhillplaza.notion.site/Television-Simulator-99-c28584f069b94f58a71b5c9fe2484dcb#8969cd7aff0e4d569efa77b15cbacf51
#
# The rest of this file is about defining a channel lineup.
####################

noSignalContent: # Optional. You can specify content to show when a channel is off the air.
  image: https://caketable.github.io/stuff/no-signal.png # 
  #bouncing-logo: https://caketable.github.io/stuff/logo-print.png #  only use as placeholder
  backgroundAudio: http://radio.plaza.one/mp3

defaultChannel: 1 # Required. The default channel to start on when visiting the page.

channels:

- number: 1
  name: Welcome
  abbr: WC
  video: https://file.garden/aUYIWVAKvQxCBY-_/database/videos/welcomeloop-caketable.mp4 
  backgroundAudio: http://radio.plaza.one/mp3
  backgroundAudioOptions:
    description: Nightwave Plaza Radio 
    nowPlayingUrl: https://api.plaza.one/status
    nowPlayingProvider: plaza-one

- number: 2
  name: test channel
  abbr: TEST # temporary maintenance
#  youtube-playlist:
#    src: UUHKj3ZT5E7wxPKRXhFAWhCQ
#    shuffle: true 

- number: 3
  name: Local News
  abbr: NEWS
  feed-reader: https://moxie.foxnews.com/google-publisher/latest.xml

- number: 4
  name: 44cast
  abbr: WX
  title: "Weather around the clock"
  description: "Stay up to date with the latest weather information. Know before you go!"
  icon: placeholders/weather.png #
#  backgroundAudio: placeholders/bgm-3.mp3
  backgroundAudio: http://radio.plaza.one/mp3
  backgroundAudioOptions:
    description: Nightwave Plaza Radio 
    nowPlayingUrl: https://api.plaza.one/status
    nowPlayingProvider: plaza-one
  weather: 
    logo: https://caketable.github.io/stuff/logo-white.png
    provider: usa
    units: imperial
    latitude: 39.30
    longitude: -84.52

- number: 5
  name: Program Guide
  abbr: GUIDE
  title: Prevue Guide
  icon: https://file.garden/aUYIWVAKvQxCBY-_/database/photos/ralsei%20smoking%20a%20fat%20blunt.png  # smoking dat blunt drs.
  noise: 0.1
  backgroundAudio: http://radio.plaza.one/mp3
  backgroundAudioOptions:
    description: Nightwave Plaza Radio 
    nowPlayingUrl: https://api.plaza.one/status
    nowPlayingProvider: plaza-one
  v-split:
    a:
      iframe: https://ourworldoftext.com/
    b:
      guide:
        theme: "1989"
        themeOptions:
          ticker: # Optional. A scrolling text bar at the bottom of the guide. Put a list of messages you want shown here.
          - "Dr. Jr."
          - "only fucking pickles"
          - "?????????????DAMN IS PICKLES CKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCKCK DRS."
          - "discord.gg/aisponge"
          - "is there directv in albuquerque"
          - "theres a monkey in my bathroom"
          - "is that the 67 mango mason mustard phonk with the gassy bowser bouncing kendrick telling jayden to explain his adrien's slowed+reverb friend group until his bus drops him off at the barbder shop haircut that costs a quarter until brazilian sleeping phonk starts sending you to ohio's resturant karma, where theres no menu and you just get the Nexus S for the nintendo switchbox 36One Series XS MAX 4G 3G from Verizprint with your boii tuff redditor scary face scares them away while you scream city boii until camman18 gets turned into the golden dandilion funk up my apple ipad until epstein catches kirk's bullet because we are charlie kirk's nephew's good answer as our son starts paying the rent with his kai cenat stream donation allowance and trying to get a corn on the cob until I start popping a zin with joe bart and send him back to gooning school with the angry beavers"
          - "NO MORE IPAD KIDS"
          - "six seven hahaha very funny pla"
          - "nexus s pla"
          - "gay"
          - "we need a hero"
          - "KINDLE FRIED DRS."
          - "mother fucking clocks"
          - "i sneezed"

- number: 6
  icon: https://file.garden/aUYIWVAKvQxCBY-_/database/photos/sonic.png
  name: Channel List
  abbr: LIST
  channel-list: 
    primaryColor: blue # no one asked
    textColor: white
    backgroundImage: https://file.garden/aUYIWVAKvQxCBY-_/database/photos/Aurora.jpg
    logo: https://file.garden/aUYIWVAKvQxCBY-_/database/photos/the%20flarg.png # 67 67 67
  
- number: 7
  name: Quant
  abbr: QNT
  daily-schedule: 
    content:
    - startTime: "18:00"
      endTime: "05:00"
      video: 
        src: https://file.garden/aUYIWVAKvQxCBY-_/database/videos/quantoffline.mp4

    - startTime: "05:00"
      endTime: "11:00"
      video:
        src: https://rhine.webchnl.live/memfs/daad2183-472a-4a6f-ac37-a2934dfccac4.m3u8
    
    - startTime: "11:00"
      endTime: "18:00"
      video:
        src: https://rhine.webchnl.live/memfs/daad2183-472a-4a6f-ac37-a2934dfccac4.m3u8


- number: 8
  name: KATS
  abbr: KATS
  iframe:
   src: https://file.garden/aUYIWVAKvQxCBY-_/scratch/html/katsauto.html
   allowInteraction: false

- number: 9
  name: guh
  abbr: GUH
  image: https://file.garden/aUYIWVAKvQxCBY-_/database/photos/guweh.png
  backgroundAudio: placeholders/bgm-3.mp3

- number: 10
  title: TELEAPPLE
  name: TELEAPPLE
  abbr: OWOT1
  iframe:
    src: https://ourworldoftext.com/telapple

- number: 11
  title: Our World Of Text
  name: Our World Of Text
  abbr: OWOT2
  iframe:
    src: https://ourworldoftext.com

- number: 12
  name: Upcoming Channel
  abbr: UNK
  title: To Be Announced

- number: 13
  name: CakeTable Commits
  abbr: GIT
  feed-reader: https://corsproxy.io/?url=https://github.com/caketable/caketable.github.io/commits/main.atom

- number: 13
  name: Google Commits
  abbr: GIT
  feed-reader: https://corsproxy.io/?url=https://github.com/caketable/caketable.github.io/commits/main.atom

